const BREAKPOINT_768 = 768;
const BREAKPOINT_480 = 480;

const VISIBLE_MOVIES_5 = 5;
const VISIBLE_MOVIES_8 = 8;
const VISIBLE_MOVIES_16 = 16;

const MOVIES_TO_LOAD_2 = 2;
const MOVIES_TO_LOAD_4 = 4;

const SHORT_MOVIES_LENGTH = 40;

export {
  BREAKPOINT_768,
  BREAKPOINT_480,
  VISIBLE_MOVIES_5,
  VISIBLE_MOVIES_8,
  VISIBLE_MOVIES_16,
  MOVIES_TO_LOAD_2,
  MOVIES_TO_LOAD_4,
  SHORT_MOVIES_LENGTH
};